# Generated by Django 2.1.2 on 2019-08-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField()),
                ('wan_id', models.IntegerField()),
                ('ip_out', models.CharField(default='NULL', max_length=30)),
                ('ip_out2', models.CharField(default='NULL', max_length=30)),
                ('ip_in', models.CharField(default='NULL', max_length=30)),
                ('vip', models.CharField(default='NULL', max_length=30)),
                ('install_id', models.IntegerField()),
                ('web_ver', models.CharField(default='NULL', max_length=16)),
                ('res_ver', models.CharField(default='NULL', max_length=16)),
                ('is_deploy', models.BooleanField(default='0')),
                ('is_open', models.BooleanField(default='0')),
                ('kf_time', models.DateTimeField(default='2025-06-12 12:00')),
                ('is_hefu', models.BooleanField(default='0')),
                ('last_hf_target', models.IntegerField()),
                ('cur_hf_target', models.IntegerField()),
                ('hf_time', models.DateTimeField(default='2025-06-12 12:00')),
                ('type', models.CharField(default='NULL', max_length=16)),
                ('status', models.BooleanField(default='0')),
                ('platform', models.CharField(default='NULL', max_length=16)),
                ('project', models.CharField(default='NULL', max_length=16)),
                ('server_dir', models.CharField(default='NULL', max_length=255)),
                ('user_info', models.CharField(default='NULL', max_length=30)),
            ],
            options={
                'db_table': 'game_info',
            },
        ),
        migrations.CreateModel(
            name='machine_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_out', models.CharField(default='NULL', max_length=30)),
                ('ip_out2', models.CharField(default='NULL', max_length=30)),
                ('ip_in', models.CharField(default='NULL', max_length=30)),
                ('vip', models.IntegerField()),
                ('idc', models.CharField(default='NULL', max_length=30)),
                ('os', models.CharField(default='NULL', max_length=64)),
                ('cpu', models.CharField(default='NULL', max_length=64)),
                ('mem', models.CharField(default='NULL', max_length=64)),
                ('swap', models.CharField(default='NULL', max_length=64)),
                ('disk', models.CharField(default='NULL', max_length=64)),
                ('usage', models.CharField(default='NULL', max_length=32)),
                ('max_deploy', models.IntegerField()),
                ('status', models.IntegerField()),
                ('platform', models.CharField(default='NULL', max_length=32)),
                ('project', models.CharField(default='NULL', max_length=32)),
            ],
            options={
                'db_table': 'machine_info',
            },
        ),
    ]
