# Generated by Django 2.1.2 on 2019-07-17 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ban',
            new_name='enable',
        ),
    ]
