# Generated by Django 2.1.2 on 2019-07-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190717_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(default='0'),
        ),
    ]
